### ISSUE TITLE
Problem when running test.py 

### ISSUE THREAD

**Issue by Fabssbtr** [pySRURGS/pySRURGS#16]
I have 8 errors and 1 failure while running test.py . The ERROR is : `FileNotFoundError: [WinError 2] The 
system cannot find the file specified` 
and the Failure is : `AssertionError: False != True`
How may I fix this issue ? 
<img width="590" alt="Capture" src="https://user-images.githubusercontent.com/64695170/80867030-45a86880-8c92-11ea-87b4-a450d5ee0dbe.PNG">

**Comment by sohrabtowfighi** [comment]
I am not sure what is wrong with your setup such that the file is not found. I know that all these tests run fine because the software's build is passing on travis-ci using a linux virtual machine. Some of the tests have random character and may sometimes fail. You can try again for the assertion error. 
For my own record keeping, this issue appears to be brought up by the same user who posted github issue #15 as demonstrated by:
![image](https://user-images.githubusercontent.com/7122606/80872061-81c4d480-8c64-11ea-8a51-26405b4c00ef.png)

**Comment by sohrabtowfighi** [comment]
The tests passed on both Windows Subsystem for Linux and regular old windows on my trial, which suggests issue has to do with your setup. If you need a clean environment to try the software, you can try installing Ubuntu 18.04 in windows using Windows Subsystem for Linux.
